# Generated by Django 2.2.5 on 2019-09-09 08:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('teste', '0004_auto_20190909_0552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='author_id',
            new_name='author',
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('author', 'content_type', 'object_id')},
        ),
    ]
